/**
 * Generates packages/api/types/plugin-api.agent.d.ts from @figma/plugin-typings
 * by stripping all comments. That file is for agent context only (saves tokens)
 * and is excluded from TypeScript so editor types stay unchanged.
 */

import { readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const require = createRequire(import.meta.url);

const apiRoot = join(__dirname, "..");
const typingsPkg = require.resolve("@figma/plugin-typings/package.json", {
  paths: [apiRoot],
});
const typingsDir = dirname(typingsPkg);
const pluginApiPath = join(typingsDir, "plugin-api.d.ts");
const outPath = join(apiRoot, "types", "plugin-api.agent.d.ts");

const { version } = JSON.parse(readFileSync(typingsPkg, "utf-8")) as {
  version?: string;
};
const versionStr = version ?? "unknown";
const generatedAt = new Date().toISOString();

const raw = readFileSync(pluginApiPath, "utf-8");

function skipLineComment(source: string, start: number, out: string[]): number {
  const n = source.length;
  let pos = start;
  while (pos < n) {
    const ch = source[pos];
    pos++;
    if (ch === "\n") {
      out.push(ch);
      break;
    }
  }
  return pos;
}

function skipBlockComment(source: string, start: number): number {
  const n = source.length;
  let pos = start;
  while (pos < n - 1) {
    if (source[pos] === "*" && source[pos + 1] === "/") {
      return pos + 2;
    }
    pos++;
  }
  return n;
}

function copyString(
  source: string,
  start: number,
  quote: string,
  out: string[]
): number {
  const n = source.length;
  out.push(quote);
  let pos = start + 1;
  while (pos < n) {
    const ch = source[pos] ?? "";
    out.push(ch);
    pos++;
    if (ch === "\\") {
      out.push(source[pos] ?? "");
      pos++;
      continue;
    }
    if (ch === quote) {
      break;
    }
  }
  return pos;
}

function stripComments(source: string): string {
  const n = source.length;
  const out: string[] = [];
  let i = 0;

  while (i < n) {
    const ch = source[i];
    const next = source[i + 1];
    if (ch === "/" && next === "/") {
      i = skipLineComment(source, i + 2, out);
      continue;
    }
    if (ch === "/" && next === "*") {
      i = skipBlockComment(source, i + 2);
      continue;
    }
    if (ch === '"' || ch === "'" || ch === "`") {
      i = copyString(source, i, ch, out);
      continue;
    }
    if (ch !== undefined) {
      out.push(ch);
    }
    i++;
  }

  return out
    .join("")
    .replace(/\n(\s*\n)+/g, "\n")
    .trim();
}

const header = `// Generated by packages/api/scripts/generate-plugin-api-agent.ts
// Accurate only at generation time; source: @figma/plugin-typings@${versionStr} (see package.json).
// Generated at: ${generatedAt}
// Excluded from TS/editor scope; for agent context only (comment-free to save tokens).
// biome-ignore-all lint: for agent context only
`;

const stripped = stripComments(raw);
writeFileSync(outPath, header + stripped, "utf-8");

console.log("Wrote %s (from @figma/plugin-typings@%s)", outPath, versionStr);
